Пользователи. Вещи.
Dobroeutro1/java-shareit pull request #1
Opened 2023-08-18 18:39 UTC by Dobroeutro1

2023-08-19 18:59 UTC, kalitva requested changes

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/errorHandler/ErrorHandler.java
> +        log.error("ERROR Validation 400! {}", errors.stream().findFirst().orElse(""));
Передай вторым параметром исключение чтобы залогировался стэкрэйс, а это - `errors.stream().findFirst().orElse("")` первым аргументом

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/errorHandler/ErrorHandler.java
> +        return new ErrorResponse("Ошибка валидации: " + errors.stream().findFirst().orElse(""));
1. И вынеси выражение ` errors.stream().findFirst().orElse("")` в переменную (выделить, ззатем shift + alt + v)
2. Сообщение пиши на английском

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/errorHandler/ErrorHandler.java
> +}
Обработчики с одинаковым статусом можешь объединить в один метод
https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-exceptionhandler

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/errorHandler/ErrorResponse.java
> +@ToString
Нам точно нужен этот `@ToString`?

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    @GetMapping("")
`@GetMapping("") --> @GetMapping`

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") Long userId, @Valid @RequestBody ItemDto itemDto) {
Давай `X-Sharer-User-Id` вынесем в константу

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Лучше обойтись без статических методов, инжектить мапперы спрингом

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long owner;
Нужно хранить не айди, а объект `User`

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long request;
То же самое, не айди, а объект

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/repository/impl/ItemRepositoryImpl.java
> +import java.util.*;
Не используй wildcard импорты.

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

Это может служить причиной лишних конфликтов при мерже веток. Настрой intellij чтобы она не схлопывала импорты

https://blog.marcnuri.com/intellij-idea-how-to-disable-wildcard-imports

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/repository/impl/ItemRepositoryImpl.java
> +    private final HashMap<Long, Item> itemHashMap = new HashMap<>();
1. `itemHashMap --> items` Не используй в названиях коллекций (и методов соответственно) слова типа `List Map Set Array` и.т.п 
2. Храни хэшмап по типу интерфейса(`Map`)

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        return itemRepository.findByUserId(userId).stream().map(ItemMapper::toItemDto).collect(Collectors.toList());
Форматируй стримы таким образом:
```java
 return itemRepository.findByUserId(userId).stream()
        .map(ItemMapper::toItemDto)
        .collect(Collectors.toList());
````

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    }
Используй методы `Opional#orElseThrow` и `Opional#map`

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserDto findById(@PathVariable("userId") Long userId) {
`public UserDto findById(@PathVariable Long userId) {`
Спринг распознает имя параметра пути по имени параметра метода

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @Email(message = "Введен неверный email!")
Сообщения для исключений - только по английски, иначе получишь в логах текст типа `????? ??? ?????? ????`

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/repisitory/impl/UserRepositoryImpl.java
> +        if (!userHashMap.containsKey(user.getId())) {
Эта проверка должна быть в сервисе

2023-08-19 18:59 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/repisitory/impl/UserRepositoryImpl.java
> +        }
Эти манипуляции тоже

2023-08-19 19:26 UTC, Dobroeutro1 commented on src/main/java/ru/practicum/shareit/errorHandler/ErrorHandler.java
> +}
Не согласен. У них разные возможности возникновения, следовательно и разная информация в логах. Либо я не понимаю, как это объединить в один метод и логировать нужную информацию (AccessError и AnyError), либо это не предоставляется возможным.
Если все ошибки с одинаковыми статусами выводить в логи одинаковым сообщением, то не вижу смысла в ErrorHandler. Можно всегда бросать RuntimeExeption со стектрейсом и не париться. Правда это менее информативно

2023-08-19 19:33 UTC, Dobroeutro1 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Почему? В доп. материалах к заданию был дан именно такой пример.

2023-08-20 16:01 UTC, kalitva requested changes

2023-08-20 16:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private final String userIdHeader = "X-Sharer-User-Id";
Более подробно о константах. Константа это `static final` поле класса c описательным названием, написанным в upper snake case, например

`private static final int MOMMA_TOLD_ME_TIMES = 1000`

Зачем нужны
https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования

Как оформляются константы
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2023-08-20 16:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public ItemDto toItemDto(Item item) {
Предлагаю назвать `toDto`

2023-08-20 16:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException(String.format("Вещь с id %x не найдена!", itemId)));
Пожалуйста, сообщение в исключении по английски

2023-08-20 16:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
То же самое

2023-08-20 16:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (user.isEmpty()) {
Это должно быть как-то так
```java
User user = userRepository.findById(userId)
        .orElseThrow(() -> new NotFound....
```

Погугли как правильно использовать `Optional`

2023-08-20 16:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +@Data
Давай вместо `@Data` использовать
```java
@Getter
@Setter
```

2023-08-20 16:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryImpl.java
> +        if (users.values().stream()
Неудобно читать, вынеси результат вычисления стрима в переменную, и в условие if передай переменную

2023-08-20 16:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +import java.util.*;
Не используй wildcard импорты.

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

Это может служить причиной лишних конфликтов при мерже веток. Настрой intellij чтобы она не схлопывала импорты

https://blog.marcnuri.com/intellij-idea-how-to-disable-wildcard-imports

2023-08-20 16:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
Поправь все опшионалы

2023-08-21 14:34 UTC, kalitva approved these changes

2023-08-21 14:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    static final String USER_ID_HEADER = "X-Sharer-User-Id";
`private`

2023-08-21 14:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        Optional<Item> item = itemRepository.findById(itemId);
Нам не нужна эта промежуточная переменная, заинлайнь ее (ctrl + alt + n в intellij)

2023-08-21 14:34 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/repository/impl/UserRepositoryImpl.java
> +        boolean isEmailExist = users.values().stream()
Лучше `isEmailExist --> emailExists`

2023-08-21 20:27 UTC, merged